### ISSUE TITLE
[BUG] Context Menu and Page Info aren't dark

### ISSUE THREAD

**Issue by SakhJack** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#104]
**Describe the bug**
Context Menu, Page Info, Clear Cookies and Clear History don't turn dark after installing Dark Theme
This wasn't an issue the first time I installed this theme (November 16, 2020)
Yes, I updated to latest version of this repo to no avail
I'm not sure exactly which FF update broke it...

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. [Install Full Dark Theme](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Full%20dark%20theme)
2. [Patch Firefox profile](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/FF83)
3. [Install Alternative tooltips](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Full%20dark%20theme/Alternative%20scrollbars%20%26%20tooltips/Alternative%20tooltips)
3. [Install Dark Addons](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/1.1.0)
4. Restart Firefox

**Expected behavior**
Every part of native UI turns dark

**Screenshots**
<details>
<summary>Context Menu</summary>

Right Click Page
![image](https://user-images.githubusercontent.com/10335530/103448604-cb523d00-4c93-11eb-87de-a4d548228ff5.png)
Right Click Tab
![image](https://user-images.githubusercontent.com/10335530/103448796-6e0bbb00-4c96-11eb-9b76-173f901a4bc4.png)
</details>
<details>
<summary>Page Info</summary>

Accessed from Padlock in address bar > Show Connection details (arrow) > More Information
![image](https://user-images.githubusercontent.com/10335530/103448588-875f3800-4c93-11eb-8c69-5b8dda2508ab.png)
</details>
<details>
<summary>Clear Cookies</summary>

Accessed from Padlock in address bar > Clear Cookies and Site Data...
![image](https://user-images.githubusercontent.com/10335530/103448688-06a13b80-4c95-11eb-8195-8f0e15c9c994.png)
</details>
<details>
<summary>Clear History</summary>
Accessed from top right menu > Library > History > Clear Recent History

![image](https://user-images.githubusercontent.com/10335530/103448718-597af300-4c95-11eb-976c-3f7dd711d8fc.png)
</details>

**Desktop:**
 - OS: Windows 10 (x64)
 - Version: FF stable 84.0.1 (64-bit)

**Additional information**
Every other element of UI is dark as expected

**Comment by Izheil** [comment]
I can't seem to reproduce the issue... Can you check if `toolkit.legacyUserProfileCustomizations.stylesheets` is `true` on your about:config?

Although it's not as much of an issue anymore, try using any lightweight theme that isn't the "default" or "light" one and see if that helps as well.

**Comment by SakhJack** [comment]
Okay I figured it out, I had custom CSS to force stop animating EME icon (spotify) that broke parts of this theme
<details>
<summary>Custom CSS</summary>
  
```css
/*disable drm logo animation*/
@namespace url("http://https://open.spotify.com"); /* only needed once */

#eme-notification-icon[firstplay=true] {
  animation: none !important;
}
```
</details>

Removing these lines solved the issue
Sorry for wasting your time

P.S. would it be possible to fix this issue and keep custom functionality?

**Comment by Izheil** [comment]
userChrome is only for the interface of the browser.
To apply to random sites, you have to add that to userContent.css.

If you use the `@namespace` one it will think that all things below apply to that namespace (it's mainly intended for xml documents rather than HMTL). 
In your case, you'd want to use `@moz-document`.

Add this at the end of your userContent.css instead:

``` CSS
/* Disable DRM logo animation on Spotify */
@moz-document url-prefix("https://open.spotify.com") {
    #eme-notification-icon[firstplay=true] {
        animation: none !important;
    }
}
```

That way it will only apply to `open.spotify.com`.
