### ISSUE TITLE
Close tab button disappears with Multi-row

### ISSUE THREAD

**Issue by emulated24** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#107]
Hi,
when patching Firefox on Mac with Multi-row, the close tab button (little X) disappears when there's more than one row.
Just verified on new installation and new profile.

Can you please fix?

**Comment by Izheil** [comment]
Are you using the patcher, or manual installation?
Also which version of Mac and multirow? I can't seem to reproduce the issue.
If you used the installer, redownload it, remove the patch, and then reinstall it.

**Comment by emulated24** [comment]
Hi,
I'm using the patcher with python3 (3.9.1).

I have macOS Mojave 10.14.6. Multirow is from 3rd of Jan. Firefox version is 84.0.2.
This was a fresh installation of all components with a new profile. Basically, all was from scratch.

**Comment by Izheil** [comment]
I changed the patcher on the 27th of january due to a permissions issue on Mac.
Use the old patcher you have to remove everything, and then patch with the lastest patcher again.

A screenshot would help as well, yes.

None of multirow files have any CSS that affects the close button of tabs, so I'm not sure what could be causing it.

**Comment by emulated24** [comment]
Okay, thx for the tip. I did as requested.
It was not showing close tab button again, but I shuffled a bit with tabMinWidth and found strange thing. When I have tabMinWidth set to 130 and 16 tabs are open, button is visible. But when I open 17th tab, close button is gone on all tabs, except the one currently selected.
Then I put 140 as tabMinWidth and the close button is always visible.

![Screenshot 2021-02-02 at 09 41 32](https://user-images.githubusercontent.com/6930087/106574751-9576d180-653b-11eb-94f9-cb7dd1433eb5.png)
![Screenshot 2021-02-02 at 09 41 16](https://user-images.githubusercontent.com/6930087/106574752-96a7fe80-653b-11eb-8954-875f09a34424.png)

**Comment by Izheil** [comment]
What you mention is the default behaviour of Firefox. Once tabs are too small the close button autohides (even without multirow).
If you want to have the tab close button always visible, you have to add this snippet to your `userChrome.css` file:

``` CSS
/* TAB CLOSE BUTTON ALWAYS VISIBLE */
#tabbrowser-tabs .tabbrowser-tab:not([pinned]) .tab-close-button {
  	visibility: visible !important;
  	display: block !important}

#tabbrowser-tabs .tabbrowser-tab:not([pinned])[faviconized="true"] .tab-close-button {
  	visibility: collapse !important;
  	display: none !important}

#tabbrowser-tabs .tabbrowser-tab[soundplaying="true"] {
  min-width: calc(var(--tab-min-width) + 18px) !important}
```
