### ISSUE TITLE
[BUG] (Full dark) about:addons page missing icons 

### ISSUE THREAD

**Issue by SakhJack** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#114]
**Describe the bug**
Add-ons menu (about:addons) is missing icons on buttons (see screenshots)

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Install [userContent.css](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Full%20dark%20theme/userContent.css) (works on fresh profile)
2. Restart browser
3. Go to about:addons
4. Observe lack of icons

**Expected behavior**
Buttons have icons appearing as normal
<details>
<summary>Default Dark Theme</summary>
  
![image](https://user-images.githubusercontent.com/10335530/112748341-8c8a0580-8faa-11eb-8993-8127798284f6.png)
</details>

**Screenshots**
<details>
<summary>Bug</summary>

![image](https://user-images.githubusercontent.com/10335530/112747681-78440980-8fa6-11eb-9068-7a11a204286e.png)
![image](https://user-images.githubusercontent.com/10335530/112747864-96f6d000-8fa7-11eb-83c5-925e5030fe1d.png)
</details>

**Desktop:**
 - OS: Windows x64
 - Version: 87.0 x64

**Additional information**
- This has been happening at least since v86 (not sure when exactly)
- Removing [userContent.css](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Full%20dark%20theme/userContent.css) solves issue
- P.S. default Dark Theme about pages are good enough for me, so if someone can tell me what to comment out as temp solution that would be great

**Comment by Izheil** [comment]
If you like the default dark theme and aren't using a custom lightweight theme, you can just remove all `about:x` sections from it and just leave the the http: rules (so delete anything above the `/*------ MOZILLA ADDONS PAGE ------*/` line).

Either way, the issue on `about:addons` was fixed now.

The theme is more aimed to be used with custom lightweight themes. It was made back on a time when the dark theme only affected the toolbar... so it might not be as necessary now except for the mozilla pages.

If you also want the custom scrollbar that comes with it, you can just re-add it at the bottom after deleting the parts you don't need from the top of the file:

``` CSS
:root{
/* These variable changes the scrollbars size and color. If you use the JS method instead, you don't need to change these.
The scrollbars-width only has 3 acceptable values, auto, thin, and none:
auto = default OS size | thin = half the width (will be hidden in about: pages) | none = hidden scrollbar */
    --scrollbars-width: auto;
    --scrollbars-thumb-color: #05a;
    --scrollbars-track-color: #252525;

/* These are the actual rules for changing the color of the scrollbar, so don't change them */
  scrollbar-color: var(--scrollbars-thumb-color) var(--scrollbars-track-color);
  scrollbar-width: var(--scrollbars-width)
}

*|* {scrollbar-width: var(--scrollbars-width)}
```
