### ISSUE TITLE
scrollbar in bookmark/history panel

### ISSUE THREAD

**Issue by NicotherZ** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#121]
Hi,
Can someone help me, can't find how to hide scrollbar in bookmark/history panel, have --scrollbars-width to "none" in UserContent hide all scrollbar escept one in bookmark/history panel.

One other thing unrelated, "Properties" or "Edit Bookmark" (don't know in english what you have) are not anymore at the bottom of context menu on bookmark panel, know to change order to put it at the bottom of context menu.

Thanks in advance for your help!

**Comment by Izheil** [comment]
That's affected by the `scrollbar-width` value in `userChrome.css` (around line 214). It accepts the same values as the `--scrollbars-width` value in `userContent.css`

**Comment by Izheil** [comment]
I just added an update to expose the same variable of `userContent.css` on `userChrome.css` to follow the same convention.

If using the updated version, change the `--scrollbars-width` variable in `userChrome.css` now.

**Comment by NicotherZ** [comment]
Trying both, not working (with your updated UserContent.css) firstly changed : --scrollbars-width to none, scrollbar still there, and changed value scrollbar-width to none (at line 172) still there too. Have done something wrong?

**Comment by Izheil** [comment]
You don't have to change userContent for the sidebar, you have to change **userChrome**.

`userContent.css` changes built-in pages for Firefox that are shown on the web-area, while userChrome changes dialogs and content that is inside Firefox UI.

**Comment by NicotherZ** [comment]
Do same on UserChrome, change nothing, scrollbar still there

**Comment by Izheil** [comment]
You are right, oddly enough `thin` works but `none` doesn't for some reason...

You can try the next best thing, on userChrome, change `--scrollbars-width` to `thin` and then both `--scrollbars-thumb-color` and `--scrollbars-track-color` to `transparent`, which will pretty much hide the scrollbars without taking much space.

**Comment by NicotherZ** [comment]
Works, thanks you!

and for the other thing ? "One other thing unrelated, "Properties" or "Edit Bookmark" (don't know in english what you have) are not anymore at the bottom of context menu on bookmark panel, know to change order to put it at the bottom of context menu." ?

**Comment by Izheil** [comment]
It used to be "Properties" before the Proton update, now it's "Edit bookmark".

You can place it at the bottom of the context menu adding this to your `userChrome.css`

``` CSS
/* Changes "edit bookmark" position to the bottom of the context menu */
#placesContext_show_bookmark\:info {
  -moz-box-ordinal-group: 2 !important;
}
```

If you have the containers addon, it will appear below the containers addon entry as well.

If you want it to be at the bottom of the context menu, but above the containers addon entry, add this other part too:

``` CSS

/* Places containers addon entry at the bottom of the bookmarks edition context menu */
#_testpilot-containers-menuitem-_open-bookmark-in-container-tab {
  -moz-box-ordinal-group: 3 !important;
}

```

**Comment by NicotherZ** [comment]
Works great, thanks !
Don't know if it's possible, but can add a separator just above "Edit bookmark" ?

**Comment by Izheil** [comment]
You can try adding a clipped border on top, so replace the previous code with:

``` CSS
/* Changes "edit bookmark" position to the bottom of the context menu & adds a separator on top */
#placesContext_show_bookmark\:info {
  -moz-box-ordinal-group: 2 !important;
  border-top: 1px solid #555;
  clip-path: inset(0 0 0 28px);
}
```

Note that you might need to change the separator color (the `#555` on the border-top rule) if you are using a different theme than the one from this repository.

**Comment by NicotherZ** [comment]
Works for separator but a bug appear with edit bookmark, the beginning of the word is cut off :

![Separator](https://user-images.githubusercontent.com/12177860/120634365-73e71180-c46b-11eb-8fce-3fcc11a51b42.jpg)
![Separator 2](https://user-images.githubusercontent.com/12177860/120634371-747fa800-c46b-11eb-8a0d-56ed72c17dd8.jpg)

**Comment by Izheil** [comment]
For some reason the text entries are misaligned on your context menus, since they should start at the start of the separators...
In either case, the highlight would indeed get chopped either way.

The only other way would have been using pseudo-selectors like `::before`, but those require the use of `position: absolute`, which for some reason hides the element on context menus, so unless we move some of the other separators down, there isn't much else that we can do.

**Comment by Izheil** [comment]
I figure that we could show a separator that is hidden when the "edit bookmark" entry is shown by targetting only the separator in it's "hidden" state (so that it's not affected when it should be shown naturally):

``` CSS
/* Changes "edit bookmark" position to the bottom of the context menu & adds a separator on top */
#placesContext_show_bookmark\:info {
  -moz-box-ordinal-group: 3 !important;
}

#placesContext_pasteSeparator[hidden] {
  -moz-box-ordinal-group: 2 !important;
  display: block;
}
```
