### ISSUE TITLE
Change context menu on bookmark panel

### ISSUE THREAD

**Issue by NasmodorN** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#125]
Hi,
Need help to change context menu (right click) on bookmark panel.
Want to put : 

"Edit Bookmark"
"Remove Bookmark"
&
"Edit Folder"
"Remove Folder"

at the bottom of the context menu with separator above "Edit Bookmark/Folder"

and remove from context menu : "Sort by name"

Thanks for your help!

**Comment by Izheil** [comment]
This should do to move the elements at the bottom with their separators positioned as they should:

``` CSS
/* Changes "edit/delete bookmark" and "rename/delete folder" position to the bottom of the context menu */
#placesContext_show_bookmark\:info, #placesContext_show_folder\:info, 
#placesContext_deleteBookmark, #placesContext_deleteFolder {
  -moz-box-ordinal-group: 3 !important;
}

/* Adds a usually hidden separator on top of the moved entries */
#placesContext_pasteSeparator[hidden] {
  -moz-box-ordinal-group: 2 !important;
  display: block !important;
}

/* Removes leftover separator of the "edit bookmark" section and the "sort by name" item */
#placesContext_deleteSeparator, #placesContext_sortBy\:name {
  display: none !important
}
```

If you ever decide that you want the "sort by name" entry again, delete the **preceding comma** + the `#placesContext_sortBy\:name` selector of the last rule (the `display: none` one), and it will appear again.

**Comment by NasmodorN** [comment]
Thanks for your help, is there a way to put first : "Delete Bookmark/Folder" and below "Modify Bookmark/Folder" ?

(For remove "sort by name", works perfectly, thanks!)

**Comment by Izheil** [comment]
Sure, replace this:

```
/* Changes "edit/delete bookmark" and "rename/delete folder" position to the bottom of the context menu */
#placesContext_show_bookmark\:info, #placesContext_show_folder\:info, 
#placesContext_deleteBookmark, #placesContext_deleteFolder {
  -moz-box-ordinal-group: 3 !important;
}
```

By this:

``` CSS
/* Changes "edit bookmark" and "rename folder" to the bottom of the context menu */
#placesContext_show_bookmark\:info, #placesContext_show_folder\:info {
  -moz-box-ordinal-group: 4 !important;
}

/* Changes "remove bookmark/folder" above the "edit bookmark" entry */
#placesContext_deleteBookmark, #placesContext_deleteFolder {
  -moz-box-ordinal-group: 3 !important;
}
```
