### ISSUE TITLE
Sizing of Tabs and Bookmarks Menu

### ISSUE THREAD

**Issue by forplan0** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#126]
What i need to change is:
1. i wanna smaller (height) for tabs? Where to find this? Also is option to get smaller space between rows of tabs...

2. And also smaller (height) of bookmarks when i open bookmarks menu 

Thank you

**Comment by Izheil** [comment]
To change the height of tabs you can either enable compact mode on `about:config` by toggling `browser.compactmode.show` as "true" and then change the density to compact on the customize page (right click empty space on the tab bar > personalize toolbar > Density combobox at the bottom of the page that will open), or apply the fixes in [here](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/issues/122#issuecomment-855477030).

For bookmarks menu, do you mean the bookmarks toolbar menu, or the bookmarks menu that can be accessed through the star icon with the line below?

**Comment by forplan0** [comment]
Wow you are quick :)

I set compact mode and is OK for me now. Thank you.

For other question i mean this https://i.ibb.co/ryTQ4YQ/12-07-2021-12-56-38.jpg
Will be better if bookmarks will be closer together.

**Comment by Izheil** [comment]
Try adding this to your `userChrome.css` file:

``` CSS
#BMB_bookmarksPopup .subviewbutton {
  padding-top: 2px !important;
  padding-bottom: 2px !important;
}
```

Change the `2px` value to something bigger if you want them less compact.

Lower than 2px they would start to look not so good.

**Comment by forplan0** [comment]
Thank you i add this and it's much better.

Also i wanna set this same thing to (bookmarks toolbar menu when i open some folder with bookmarks)

What is code for this?

**Comment by Izheil** [comment]
This should do:

``` CSS
/* Changes the sizing of the bookmarks toolbar menu items */
#PlacesToolbarItems .bookmark-item {
  padding-top: 1px !important;
  padding-bottom: 1px !important;
}
```

If you feel like it's still too padded, set them as 0 and they will be the most compact possible.
