### ISSUE TITLE
[BUG] Page Information Window isn't fully dark

### ISSUE THREAD

**Issue by Elaborendum** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#127]
**Describe the bug**
I only used the Page Information Window part of the userChrome of the Proton Full Dark theme, and for some reason it doesn't look at all like the image in the readme. Instead the tables in "General" and "Media" look mostly white and very hard to read.

Should I use the full userchrome instead?

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Add "Page Information Window" section to userChrome.css
2. Restart Firefox
3. Open the page information window

**Screenshots**
The table in Media:
![imagen](https://user-images.githubusercontent.com/71190696/125389436-d1258b00-e366-11eb-8abe-3b7e8309e574.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: FF89.0.2

**Additional information**
 - I have previous code in userChrome.css, but since the Page Information Window looks normal without this theme I don't know if that's also messing with it.

**Comment by Izheil** [comment]
Some elements use a common part like those treechildren node elements:

``` CSS
/* This is a fix for treechildren that might look whiteish */
treechildren::-moz-tree-row, dialog richlistitem {background: transparent !important}

/* This changes all treechildren elements highlights (list-like elements) */
treechildren::-moz-tree-row(hover), dialog richlistitem:hover {
  background: var(--Lists-treechildren-hover-bg) !important;
  border: 1px solid var(--Lists-treechildren-hover-border) !important}

treechildren::-moz-tree-row(selected), dialog richlistitem[selected] {
  background: var(--Lists-treechildren-selected-bg) !important;
  border: 1px solid var(--Lists-treechildren-selected-border) !important;
  color: var(--Lists-treechildren-selected-txt) !important}
```

^ You will have to change the color of the element highlights instead of the variables that are set, since they assume you'd be using all of the file content.

The userChrome.css is intended to be used as a whole, not as much as a "pick what you like", so you will have to find the common parts of the things you want to use if you want to only apply some things.
