### ISSUE TITLE
[BUG] Multirow tabs looses scroll position after a fullscreen video

### ISSUE THREAD

**Issue by Celelibi** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#132]
**Describe the bug**
On youtube, putting a video in fullscreen and then exiting fullscreen scroll the tab bar back to the top.

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Install MultiRowTab-scrollable-autohide.uc.js
2. Open enough tabs that you have to scroll down.
3. Go to youtube and play a video fullscreen
4. Exit fullscreen, your tab bar is scrolled back to the top.

**Expected behavior**
The scroll bar should stay scrolled where it was.

**Desktop (please complete the following information):**
 - OS: Linux Debian testing
 - Version Firefox 78.12.0esr

**Additional information**
I made a few customisations to the code and style. Although I don't think they matter, here is what they are:
```javascript
var scrollbarSize = "none";
```
```css
     #tabbrowser-tabs[overflow="true"] > #tabbrowser-arrowscrollbox > #tabs-newtab-button,
     #TabsToolbar:not([customizing="true"]) #tabbrowser-tabs[hasadjacentnewtabbutton] > #tabbrowser-arrowscrollbox > #tabs-newtab-button {
-        display: inline-flex !important;
+        display: inline-flex;
     }
```

My userChrome.css:
```css
/* Config for Multirow-tabs from 'Quantum-Nox-Firefox-Dark-Full-Theme'. */
:root {
        --tab-growth: 0;
}

#tabbrowser-arrowscrollbox {
        padding-left: 20px;
}

#scrollbutton-up, #scrollbutton-down,
#new-tab-button,
#tabs-newtab-button,
.tabbrowser-tab .tab-close-button
{
        display: none;
}

/* I call this a bug. */
:root {
        /* This should have never been implemented. */
        -moz-window-dragging: no-drag !important;
}
```
