### ISSUE TITLE
[BUG] uBlock Origin "My filters" notice and related questions in support.mozilla.org are hard to read

### ISSUE THREAD

**Issue by Elaborendum** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#137]
**Describe the bug**
In UBO's settings, if you try to leave to, for example, "My rules", after you make an edit in the "My filters" without saving it, you will get a notice about it. The background of this notice is a very light shade of yellow, which makes the text on it very hard to read.

On the other hand, when you go to a question on support.mozilla.org, there's a sidebar that directs you to similar questions. In this case, the text is a rather dark shade of grey, which makes it uncomfortable to read against the dark background.

**To Reproduce**
UBO:
1. Open UBO's settings
2. Go to the "My filters" pane and make any edit
3. Try to leave to another pane, like "My rules"
4. See notice

SUMO:
1. Go to a question, for example https://support.mozilla.org/en-US/questions/977330
2. Scroll down and see the related questions in the "See also" section in the right sidebar

**Screenshots**
![imagen](https://user-images.githubusercontent.com/71190696/131766557-dfcfc2cb-e4eb-45a3-b56f-7282a4d4701f.png)
![imagen](https://user-images.githubusercontent.com/71190696/131766561-1f1692de-7367-4b23-b240-147231d981ca.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version Firefox 91.0.1

**Comment by Izheil** [comment]
The Ublock issue should be fixed with the lastest commits.

As for the mozilla support page, it should show as blue by default:

![imagen](https://user-images.githubusercontent.com/33794458/131790820-8e4c4c05-856a-43b6-b91a-b52b9b08ce64.png)

It uses the value of the common variable `--in-content-link-color`, so if you changed it, it will get changed everywhere, including mozilla support pages.

If you don't want to use the link color everywhere and just want that sidebar text color changed, add this to the bottom of the mozilla support page section in `userContent.css`:

``` CSS
/* Normal color for links on sidebar */
#related-content > *[class^="related"] a {
    color: #09f !important}

/* Hover color for links on sidebar */
#related-content > *[class^="related"] a:hover {
    color: #0cf !important}

/* Active or on-click color for links on sidebar */
#related-content > *[class^="related"] a:active {
    color: #0070aa !important}

/* Visited color for links on sidebar */
#related-content > *[class^="related"] a:visited {
    color: #007acc !important}
```
^ Change the colors to any you like.
