### ISSUE TITLE
[BUG] FF 92 a row with pinned tabs is thicker

### ISSUE THREAD

**Issue by 532910** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#138]
Starting with FF92, a row with pinned tabs is wider:
![image](https://user-images.githubusercontent.com/14617699/132796113-6580971f-939d-45d4-bd70-8d83505e134e.png)

When no pinned tabs all works as expected:
![image](https://user-images.githubusercontent.com/14617699/132796121-d89925c9-f06e-4c06-8ddb-cf863cf72749.png)

**Expected behavior**
The same height for all tabs: pinned and normal.

Debian sid, 92.0-2

`userChrome.css`:
```Css
@media (-moz-proton) {
	.tab-background {
		margin: 0 !important;
		padding: 0 !important;
	}
	.tabbrowser-tab {
		margin: 1px !important;
		padding: 0 !important;
	}
	.tab-context-line {
		-moz-box-ordinal-group: 2 !important;
		margin: 3px !important;
	}
}
```
