### ISSUE TITLE
[BUG/FEATURE REQUEST] Inner-padding lowered for more compact rows

### ISSUE THREAD

**Issue by Thrakk** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#140]
**Describe the bug**
There is essentially two places you can customize in the MultirowTab script.  **:root** and **#TabsToolbar {**
I use 2 max tab rows in :root and my other customization is this:
    
     #TabsToolbar {
        --tab-min-height: 16px !important; /* default inherit */
        /* You don't need to change this last one but I did */
        --toolbarbutton-inner-padding: 1px !important; } /* default inherit */

The problem is that editing inner padding to be more compact will force max tab rows to stay at 'X' (2 in my case) even when you only have 1 rows of tabs. What this looks like is a blank row beneath a single row of tabs that would normally have been automatically compressed away if I left inner-padding as 'inherit'.
   
_________________________________________________________________________________
Desktop: Windows
Firefox: 92.0. 
Proton disabled through chrome and about:config (to be more compact)

**Comment by Izheil** [comment]
The inner padding variable isn't intended to be changed, which is why it says "you don't need to change this", and also why there isn't any explanation of it on the instructions above that fragment.

20px is the minimum height on the `--tab-min-height` variable that won't give you any trouble as far as you have compact mode enabled on about:config, which is already quite small.

Editting past that would require many more fixes than just the padding, like changing the favicon sizing, the close/max/min buttons which would keep the size of the tabs row bigger than the tabs, and eventually needing to change the font size.

I don't see much reason to implement that, given that 20px already gives enough small size, and that I'd have to add too many alterations for each range of size that people wanted to add.

Either way, I'll add the clarifications on the details of multirow tabs.

**Comment by Thrakk** [comment]
Thanks for responding. I do like how compact everything is already. I always use [menu bar / bookmark toolbar items] as one row, and I magnify everything in Windows to 150% because of my eyesight. 

I checked and 150% is 28 pixels larger than 125%. Maybe you get why I like Firefox to be extra compact. Things are pretty good the way I have them so I will keep the empty row and 16px min height. Thanks for keeping the multirow script up-to-date!

**Comment by Izheil** [comment]
Well, I checked it before I tried to see if I could do something similar to another issue like this that happened when having just one row with only pinned tabs without any luck, but I decided to take another look to see if I could do something different, and looks like this time it's working right (at least with the 16px sizing you were using on the example).

I added the updated version to the repo, so you should now be able to do the same changes you did before and they should work without creating an empty row.
I'll recompile the patchers in a little while, so if you want to update now, get the multirow files from the [multirow tabs](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Multirow%20tabs) folder.

You will need to uncomment the lines related to buttons padding for smaller tabs for them to apply, so instead of:

``` CSS
    /*  These below control the padding of the new tab button and min/max/close buttons respectively.
        YOU DON'T NEED TO CHANGE THESE unless you want to use values of --tab-min-height lower than 20px. 
        Before changing them, you need to UNCOMMENT the 2 rules below for them TO TAKE EFFECT. */

    /*
    #TabsToolbar {
        --toolbarbutton-inner-padding: inherit !important;
    }

    .titlebar-buttonbox .titlebar-button {
        padding-top: 8px !important;
        padding-bottom: 8px !important;
    }
    */
```

Once uncommented and changes made it should look like:

``` CSS
    /*  These below control the padding of the new tab button and min/max/close buttons respectively.
        YOU DON'T NEED TO CHANGE THESE unless you want to use values of --tab-min-height lower than 20px. 
        Before changing them, you need to UNCOMMENT the 2 rules below for them TO TAKE EFFECT. */

    #TabsToolbar {
        --toolbarbutton-inner-padding: 0 !important;
    }

    .titlebar-buttonbox .titlebar-button {
        padding-top: 4px !important;
        padding-bottom: 4px !important;
    }
```
The reason why it's commented by default even when they have the default values that Firefox uses is that those could cause issues in different OS's, since not all of them have the same padding around the min/max/close buttons, and the inner-padding isn't really needed to be changed unless you want more compact tabs.
