### ISSUE TITLE
[BUG] MultiRowTabLiteforFx - Fixed width causes the last tab of a row to create new row leaving a gap above

### ISSUE THREAD

**Issue by albino1** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#142]
**Describe the bug**

To be clear, this might not be a "bug" per se, but it didn't used to happen pre-Proton, and it might just be the way it is now, so feel free to close if that's the case.

Essentially if you set the tab width to fixed using a `--tab-growth` of `0` in `MultiRowTabLiteforFx` then, when you get to the end of a row, the last tab shifts down to the next row leaving a gap at the end of the row above.  I think a screenshot would be the easiest way to explain this, so I put one in the screenshots section below.

I think this is possibly because the last tab has the new tab button attached, and there's not enough room for it, so it gets bumped to a new row.

Edit: I think that the new tab thing is definitely what's happening.  Testing again on my PC with a 4K monitor if I resize the window around I can make the last tab jump to the new row based on how much real estate there is for the new tab button on the right.  So this is probably isn't fixable other than maybe if I hide/disable the new tab button some how.

**To Reproduce**
1. Use `MultiRowTabLiteforFx.uc.js`
2. Change `--tab-growth` to `0`
3. Create new tabs across the row until it's forced to start a new row.

**Expected behavior**
The bottom tab row is full of tabs, however the tab row just ends up one short and a new tab row is created.

**Screenshots**

![multirowbug2](https://user-images.githubusercontent.com/12164957/133906367-dee50f64-0f42-4e86-908c-e3a9ec3be9b3.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: Firefox 92

**Comment by Izheil** [comment]
It's due to some fix to prevent the new tab button to start a new row alone.
If you are okay with the new tab button starting a new row on it's own, you can remove the fix from the file removing the following lines or commenting them out:

``` CSS
/* This fixes the new tab button overflowing to the new row alone */
    #tabs-newtab-button {
        margin-left: -32px !important} 
        
    .tabbrowser-tab[last-visible-tab="true"] { 
        margin-right: 32px !important}
```

The alternative would be placing the new tab button on the left of the tabs on customize mode while also removing those lines from the file, so that the new tab button wouldn't start a new row on it's own, also not leaving new rows starting on their own (since those lines add the space that the new tab button would take to prevent it from starting new rows alone).

**Comment by albino1** [comment]
Ah, yeah, that explains it, thanks for such a thorough reply.  I just tested commenting out those lines and it works just like you described, and seems like a better alternative for my use case.

I wonder if it's possible to just hide the new tab button all together? I always just ctrl+t so I never even use it.

**Comment by Izheil** [comment]
Sure, just add these lines on your `userChrome.css` or inside the CSS part of multirow:

``` CSS
/* Hides new tab button next to the last tab */
#tabs-newtab-button > image {
  display: none !important} 
```

Just remember that when a new release of Multirow is out there due to any problem with any upcoming version of Firefox that may break it, you will have to remove the margins again, and add those lines if you add it to your modified multirow instead of userChrome.
