### ISSUE TITLE
[BUG] Pinned tabs too tall

### ISSUE THREAD

**Issue by simoncarne** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#146]
**Describe the bug**
I have installed the most recent version of MultiRow Tabs (29 Oct 21). My *pinned* tabs are appearing much taller than the non-pinned tabs and much taller they did with the previous version that I was running (6 June 21, I believe).

**To Reproduce**
Replacing `MultiRowTab-scrollable.uc.js` with the latest version. 

**Expected behavior**
I expected the pinned tabs and non-pinned tabs to be the same size as each other. Is there some code in a CSS file that I need to change to fix the problem?

**Screenshots**
In the screenshot below, the first ten (narrow) tabs in the top row are all pinned. The rest are unpinned.
![Pinned tabs too tall](https://user-images.githubusercontent.com/33954467/139735576-692b3cdb-d447-443f-befa-541c3b97cc44.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Firefox 93 (64 bit)

**Comment by Izheil** [comment]
I updated both multirow and rounded-tabs files.
If you were using some other script to get non-padded tabs, you might need to add this code snippet to it, or to your userChrome.css file:

``` CSS
/* Makes sure pinned tabs won't take more space than they should */
.tabbrowser-tab[pinned] {
  max-height: var(--tab-min-height) !important;
}
```
