### ISSUE TITLE
[BUG] No background color inside the tab dropdown list

### ISSUE THREAD

**Issue by AuRiMaS666** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#148]
After upgrading my Windows to 21H2 I've noticed that the background color in the tab dropdown list is missing.

![2021-12-05_20-31-47](https://user-images.githubusercontent.com/59185222/144759497-223e97dd-bd2b-4aa4-b3af-1c96694b39eb.png)

Also, the same thing was happening with Adguard Assitant's background, but coincidentally this extension received an update after a long time which introduced dark mode and the issue went away.

![2021-12-05_20-32-54](https://user-images.githubusercontent.com/59185222/144759669-1ee5a466-fc2d-40bf-9484-d3a5099f089d.png)

I took a look at a fresh install of FF with default and Lepton themes and it doesn't have this problem, so I guess this is something specific to this theme.

P.S. While we are talking about background colors, may I suggest adding dark mode support for a bookmark syncing addon like EverSync or Floccus?

**Comment by Izheil** [comment]
It should be fixed on the lastest commit.

As for the addons, I only theme addons by request, so unless you are requesting a dark theme for one of them, I don't think I will, considering that Firefox already has bookmarks syncing support.

**Comment by AuRiMaS666** [comment]
Thank you, it does work fine now.

It would be nice to have EverSync's popup themed for overall completeness sake, as it's the only white addon I currently have and seems pretty basic to do. Floccus seems to be more complex and, to be honest, I haven't switched to that one yet.

![2021-12-06_09-32-58](https://user-images.githubusercontent.com/59185222/144808135-c4fd3e3a-fa38-498f-b03f-ecae68719ae7.png)

I know FF has sync, but it's just my personal preference to use a 3rd party tool to be able to drop bookmarks between FF and Chromium easily.

**Comment by Izheil** [comment]
For what I see the addon hasn't been updated in 2 years, and asks for some questionable permissions, also being related to FVD speed dial, which was taken down from AMO for privacy issues some time ago... so I wouldn't recommend using it.

Still, if you want to go ahead, here is the theme for it:

``` CSS
/*------ EVERSYNC ADDON ------*/
@-moz-document url-prefix(moz-extension://EVERSYNC-UUID-GOES-HERE/popup.html) {
  html, body {
    background-color: #222 !important;
    color: #ccc !important
  }

  .fvdButton:not(.main) {
    background-color: #333 !important;
    background-image: none !important;
    color: #ddd !important;
    border-color: transparent !important;
    text-shadow: none !important;
  }

  .fvdButton:not(.main):hover {
    background-color: #444 !important;
    color: #fff !important;
  }

  .fvdButton:not(.main):active {
    background-color: #111 !important;
    color: #fff !important;
  }

  .fvdButton.main {
    background-color: #0050dd !important;
    color: #fff !important;
    text-shadow: none !important;
    border-color: transparent !important;
  }

  .fvdButton.main:hover {
    background-color: #0084ff !important;
  }

  .fvdButton.main:active {
    background-color: #0020cc !important;
  }
}
```
