### ISSUE TITLE
moving the window

### ISSUE THREAD

**Issue by chwba** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#31]
### First of all Thank you for this, very nice work.

I can move the window only when not maximized and the handle is only at the upper top left corner.

- How can I enable moving the window when maximized? 
- How can I make it so that the handle for moving the window is available on the full range of the upper edge of the top bar?

I remember fixing the handle availability problem like so:
(changing from 6px to 10px)
```bash
#main-window[sizemode="maximized"] #titlebar{
  margin-bottom:calc(10px + var(--tab-min-height)*-1) !important;
}
```
Im not sure if thats the correct approach with your configuration.

* Then I also really like the css-hacks from [here](https://github.com/MrOtherGuy/firefox-csshacks), especially the
[status_inside_url_urlbar.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/status_inside_urlbar.css). It doesn't integrate so nice color-wise, how could I optimize it to integrate in your skin a little better.

* How can I achieve to integrate these two effects:
[button_effect_scale_onclick.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/button_effect_scale_onclick.css) and [button_effect_scale_onhover.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/button_effect_scale_onhover.css)?

* How could I modify your skin to integrate [toggle_bookmarksbar_with_alt.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/toggle_bookmarksbar_with_alt.css) while modifiyng the toggle hotkey to something else and also showing all rows of the bookmarks at once when toggling?

**Comment by chwba** [comment]
Thank you for the quick and detailed reply. I have edited my initial post, crossed everything fixed and marked all previously written text italic.

**Comment by chwba** [comment]
After some trial and error I found that if I implement the multi-row toolbar like so it is at least possible to click the bookmarks. After clicking it will hide the bookmarks again and load the page. Still got the following problems:

- In fullscreen mode the bookmarks wont show at all (black background, no content but it does resize though)
- In windowed mode sometimes I need to resize the window to make the bookmarks visible

```css
/* Multi-Row Bookmarks Toolbar */
  /* Menubar in Toolbar (required) */
  #toolbar-menubar:not([inactive]) ~ #TabsToolbar{
	margin-left:300px !important;
	margin-top: -26px !important;
}
:root[sizemode="maximized"] #toolbar-menubar:not([inactive]) ~ #TabsToolbar{
	margin-top: -28px !important;
}
 /* Menubar in Toolbar - END */
  
/* Switch on multi-row */
#PersonalToolbar {
/* Provide room for up to 4 rows at 26px */
max-height: 104px !important;
}
#PlacesToolbarItems > box {
display: inline-block !important;
}
#PersonalToolbar #PlacesToolbarItems {
/* Override hiding */
overflow-x: visible !important;
overflow-y: visible !important;
/* Add a little cushion */
padding-bottom: 1px;
}
#PersonalToolbar #PlacesToolbarItems .bookmark-item {
/* Reduce padding on individual bookmarks to fit rows closer together */
padding-top: 1px !important;
padding-bottom: 1px !important;
}
/* Switch on multi-row - END */


/* TOGGLE WITH ALT */
#main-window[sizemode="normal"]:not([customizing]) #PersonalToolbar{ 
  transition: margin 0.15s ease-in-out 50ms, z-index 16ms linear 100ms!important;
}

:root:not([customizing]) #toolbar-menubar[inactive] ~ #PersonalToolbar:not(:hover){
  visibility: collapse !important}

:root:not([customizing]) #toolbar-menubar:not([inactive]) ~ #PersonalToolbar,
:root:not([customizing]) #navigator-toolbox:hover > #PersonalToolbar {
  visibility: visible !important}
/* TOGGLE WITH ALT END */
/* Multi-Row Bookmarks Toolbar - END */
```
