### ISSUE TITLE
[BUG] Multi Row Tabs does not work anylonger on FF 76

### ISSUE THREAD

**Issue by Sabine5034** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#64]
Hello Izheil,
After upgrading FF 75 to FF 76  **Multi Row Tabs** does not work anylonger. Only 1 row is shown, arrows right and left for scrolling horizontally and an arrow down for a tabs-list (also the plus-button is shown). (I think the original FF bar is like that? ...forgot it.)

Anything that I can do to make it work again?
Oh b.t.w. it worked very well on FF 75 and I have been very happy with this solution :-). Thank you very much for your excellent work.

 - OS: W10 pro 64
 - Version [e.g. FF76]

Thanks in advance,
Wil

**Comment by Izheil** [comment]
Thank you for using this version!

It seems to be working for me on windows 10, did you install manually or through the patcher?

If using the patcher make sure you are using the patcher of the FF76 tag, that the paths inside are pointing to the right profile folder and that you selected multirow to re-patch.

If installing manually, make sure you are using the [lastest version from the master branch](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Multirow%20tabs), (since sometimes when exiting from the releases page you might get redirected to an old tag version like FF75 instead of the master branch)

**Comment by Sabine5034** [comment]
I installed through the patcher (version Multirow-Patcher-Quantum-Nox-Installer-Win-1.4.4.exe) that I also used for FF75. Where do I find the one you mentioned?
And how do I "re-patch"? I can't find this function on the patcher I've been using sofar.

**Comment by Izheil** [comment]
Currently the patcher doesn't autoupdate, nor fetches the files online (since some antiviruses already seem to flag it, I prefered to not make people worry more seeing that it connects to the repo to fetch updated versions).

You should be using the [lastest patcher](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/FF76) from the [releases page](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases) when updating (which is currently the 1.5.1 one).

I'm currently remaking the patcher, which should allow for the files to autoupdate on their own so that the patcher only needs to be run once instead of after each file breaks in a new Firefox release (it will take me a while, since I currently don't have too much free time), but right now, people still need to download the patcher to get the most updated version of the files.

By "re-patch" I just meant to patch the same function you had already as if you were patching for the first time.

**Comment by Sabine5034** [comment]
works again now :-))) It was the wrong patcher I had used. Thanks a lot for your help and have a corona-free weekend, wherever you are :-).

Wil

**Comment by Izheil** [comment]
You too!
Cheers!

**Comment by Sabine5034** [comment]
me again...
as it seems, the autohide-function does not work correctly. I have set scrollable rows to 3 rows and choose "autohide" on the patcher. I do have tabs in total spread over 7 rows. Only the scrollbar hides when I leave the tabs bar and pops up again when I enter the tab bar.
Also the tabs have now a leight grey bar (like a shadow) on their upper side. Strange that, I did not see that on FF75.
Sorry to bother you again (even on a sunday :-) )

**Comment by Sabine5034** [comment]
apropos.. how can I attach screenshots to the comments?

**Comment by Izheil** [comment]
You can just drag a picture to the comment section and it will upload it.

The function of the autohide version is to hide the scrollbar due to a bug some people was experiencing in unlimited scrolling pages like reddit or facebook, where they couldn't drag the scrollbar with the mouse. If you don't drag the scrollbar often and instead use the mouse wheel, you shouldn't need it.

As for the grey bar... see if it still happens without multirow, or if it depends on your theme, since I don't see anything out of the ordinary (multi-row doesn't add any visual element that could cause that at least, at most it removes some elements).

**Comment by Sabine5034** [comment]
I obviously misunderstood the "hiding" function. I Thought the function was to hide the total tab bar (which would make sense too me, as it would make more space available for the site shown)  and not only the scrollbar. No problem though. I've installed now the "normal" version where the scrollbar stays visible. Fine to me. 

As of the grey bar. I tried many things, even another Theme (I'm using SC_2.0 Theme), but no improvement. See screenshot below:
![upper tabs too high resp tab bat reaches in bookmark bar](https://user-images.githubusercontent.com/62470072/81499020-a7875480-92c8-11ea-9049-fc1ba3f9bbe5.jpg)
To me it seems that the bar itself is positioned too high so it reaches in the bookmarks bar. It touches almost the Folder icons (as you can see) in the bookmarks bar. It does not do this when MRT is unpatched.

**Comment by Sabine5034** [comment]
another screenshot just for better understanding

**Comment by Sabine5034** [comment]
sorry forgot screenshot. Here it is:
![just for better understanding with dark theme](https://user-images.githubusercontent.com/62470072/81500650-e66ed780-92d3-11ea-9c71-a560c877903e.jpg)

**Comment by Izheil** [comment]
For what I see you are using a custom `userChrome.css` apart from the files here.
This is how it shows the default dark theme without any other modification apart from multirow and tabs below fixes from this repo:

![Sin nombre](https://user-images.githubusercontent.com/33794458/81513242-34f99180-9327-11ea-878f-0f12af14d1b4.png)

Somewhere in your `userChrome.css` file they set those borders, while also removing the top line in the currently active tab (probably in the "rounded tabs" fix userChrome of the page of the screenshot).

As for tabs below... yes, it has had some issues after FF70+... It's optimized for 1920x1080 screens (as you can see in my screenshot), but if yours has a different resolution it might have that problem. 
You'll have to change some values inside `tabs-below.as.css` inside your [chrome folder](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Chrome-and-Root-folders#chrome-folder):
``` CSS
/* These control the space to leave on top of the window for the menu toolbar.
   Don't change the #navigator-toolbox margins to anything lower than 35px on maximized window
   and 28px on normal window if you want to see the menu bar 
   on top of all bars */
#main-window[sizemode="maximized"] #navigator-toolbox {margin-top: 35px !important}
#main-window[sizemode="normal"] #navigator-toolbox {margin-top: 28px !important}
```

^ Change the 35px for maximized window margin-top rule to something greater like 40px, and the 28px from the "normal" window to 33px if the problem also happens on resized windows. If it needs more or less space keep playing with those 2 values until it's aligned correctly:

``` CSS
/* These control the space to leave on top of the window for the menu toolbar.
   Don't change the #navigator-toolbox margins to anything lower than 35px on maximized window
   and 28px on normal window if you want to see the menu bar 
   on top of all bars */
#main-window[sizemode="maximized"] #navigator-toolbox {margin-top: 40px !important}
#main-window[sizemode="normal"] #navigator-toolbox {margin-top: 35px !important}
```

You can open your profile folder through the patcher directly (in the patch status area above the patch or remove patch buttons), or through about `about:profiles`, opening the root folder of your currently used profile.

**Comment by Sabine5034** [comment]
Hi, and Good Morning,
Thanks for your friendly response (it seems you’re a night-worker  ).
I’ve (temporarily) deleted the Rounded Tab Corners css and you’re right, it obviously is caused by this modification: https://github.com/FrankConijn/Firefox-Quantum-Rounded-Tabs . (Sorry Frank) See screenshot:
![without Rounded Corners css](https://user-images.githubusercontent.com/62470072/81543669-ae6ca080-9376-11ea-989a-9b2e0a9713a3.jpg)

Now, I don’t really need these rounded corners, the only thing I find very helpful in this modification is the thin separation bar between the tabs. If this could be done in the Multi Row Tabs css, I would certainly prefer that.

About Tabs Below:
I played a bit with the settings you suggested for Tabs Below but that only changes the width of the menu-bar and does not move the Tabs bar to a lower position. 
But..., doing this playing I found out that the phenomen with the “upper grey bar” only occurs when the window is maximized. With (slightly” minimized window, the tab bar is normal. See screenshot. 
![with (slightly) minimized window](https://user-images.githubusercontent.com/62470072/81543686-b4628180-9376-11ea-9dbc-a32b3a3724cc.jpg)

**Comment by Izheil** [comment]
Aaah, you are right, I copied the wrong part of the code (I guess I misplaced the code because of the similarity of the selectors), my bad.
The right part to modify for tabs below is this one:

``` CSS
/* You may need to change this to remove padding above tabs */
#main-window[sizemode="maximized"] #titlebar {margin-top: -8px !important} 
#main-window[sizemode="normal"] #titlebar {margin-top: -1px !important}
```
Change the margin top to something higher on the maximized one, since it's the only one giving you trouble. Something like `-2px` or `0px` should work.

``` CSS
/* You may need to change this to remove padding above tabs */
#main-window[sizemode="maximized"] #titlebar {margin-top: -2px !important} 
#main-window[sizemode="normal"] #titlebar {margin-top: -1px !important}
```

As for tab borders, you might want to add this to your `userChrome.css` file to add a line border:

``` CSS
/* Tabs border color */
.tabbrowser-tab {border-right: 1px solid rgba(0,0,0, .15) !important}
```
This should add a translucid black border to the right of each tab (since the first tab in each row doesn't need a left border, you will see the border in both sides of all other tabs).

If you instead use a dark theme, you will need to use a white border, so change the color value in the code to `rgba(255,255,255, .15)`

``` CSS
/* Tabs border color */
.tabbrowser-tab {border-right: 1px solid rgba(255,255,255, .15) !important}
```

The final `.15` value controls opacity, so a value of 1 means completelly opaque color, and 0 would mean completelly transparent.
 
The other 3 values follow the schema of red, green, and blue, and you can test those in [this page](https://www.w3schools.com/colors/colors_picker.asp) (it will give you the rbg code, which is like the rgba code but without the opacity control, so just copy the 3 first values into the rgba one if you want to use translucid colors).

**Comment by Sabine5034** [comment]
Everything perfect now !! I've removed the Rounded Corners mod. from the css. Minimized and maximized windows are both fine now. The blue borderline on the top of the focussed tab is back again. Very nice!

Also the thin lines between tabs are perfect!! Thanks a lot for that code :-) . 

Last question: can I also create a thin border-line at te bottom of the tabs? I tried it with the same code as for the right border lines and just changed "border-right" in "border-bottom", but that didn't work.

And very last question: do you know by chance of any css to change the color of the background and the text of the url-bar ? 

Otherwise, thank you very, very much for your help. I've appreciated it very much !! :-)

**Comment by Izheil** [comment]
Changing it to `border-bottom` should do the trick, just make sure that when using more than 1 rule you finish each rule with `;` like this (the last rule inside the selector doesn't need it):

``` CSS
/* Tabs border color */
.tabbrowser-tab {
    border-right: 1px solid rgba(255,255,255, .15) !important;
    border-bottom: 1px solid rgba(255,255,255, .15) !important}
```

As for the code to change the urlbar colors, these are a few:

``` CSS
/* Url and search bars */
#nav-bar, #searchbar {
  --lwt-toolbar-field-background-color: rgb(61,61,63) !important;
  --lwt-toolbar-field-focus: rgb(71,71,73) !important;
  --lwt-toolbar-field-color: #ccc !important;
  --lwt-toolbar-field-focus-color: var(--lwt-toolbar-field-color) !important;
  --lwt-toolbar-field-border-color: #333 !important;
  --toolbar-field-focus-border-color: #666 !important;
  --urlbar-popup-action-color: rgb(90,170,230) !important;
  --urlbar-separator-color: #666 !important;
  --autocomplete-popup-highlight-background: rgba(100,100,100,0.4) !important;
  --autocomplete-popup-highlight-color: #ddd !important;
}

/* This changes the links inside the urlbar suggestions box */
.urlbarView-url {color: rgb(90,170,230) !important}
```
Each does the following:
* `--lwt-toolbar-field-background-color` -> changes the background when inactive
* `--lwt-toolbar-field-focus` -> changes the background when focused
* `--lwt-toolbar-field-color` -> changes the text color when inactive
* `--lwt-toolbar-field-focus-color` -> changes the text color when focused
* `--lwt-toolbar-field-border-color` -> changes the border of the urlbar when inactive
* `--toolbar-field-focus-border-color` -> changes the border of the urlbar when focused
* `--urlbar-popup-action-color` -> changes the color of the "switch to tab" action in the urlbar autocomplete popup
* `--urlbar-separator-color` -> changes the separator bars between the shield/lock, and the urlbar/suggestions in the autocomplete popup
* `--autocomplete-popup-highlight-background` -> changes the background color of the autocomplete highlighted item (the selected one)
* `--autocomplete-popup-highlight-color` -> changes the text color of the selected item

The last one with the `.urlbarView-url` selector changes the link colors on the autocomplete popup in the address bar.

If you don't want those colors to apply to the search box, remove the `#searchbar` selector and the comma before it. If you don't have it enabled you don't have to worry about it.
