### ISSUE TITLE
[BUG] PersonalToolbar grows vertically

### ISSUE THREAD

**Issue by bitbooster** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#65]
**Describe the bug**
On my Linux Mint 19.3 I recently updated the packages and among those is Firefox, which upgraded the version to 76.0. I've done a 'git pull' on this repo (to commit c8d18520fa8f19d36ad6c1ed31ff6d2f446c2ba1)  and re-run the installer.
Now oddly, the bookmark toolbar is shown vertically.
Last time I updated MultiRowTabs was around last February, I think.

**To Reproduce**
As I wasn't sure whether it was because of some customization of my user/profile, to start clean:

- I created a new Linux user, and switched to it
- launched Firefox once to create the profile
- ran the MultiRowTab installer, selecting only Multi-row tab option
- started Firefox again.
- opened a few websites (youtube, ebay, amazon) and bookmarked them to toolbar.
- the bookmarks are stacked vertically

**Expected behavior**
- I would expect the toolbar to grow horizontally as it was before.

**Screenshots**
![quantum](https://user-images.githubusercontent.com/553677/81480087-02b93880-9230-11ea-96fa-c1b390e83782.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Version: 76.0+linuxmint1+tricia

**Comment by Izheil** [comment]
That should only happen if you are using an outdated code of multirow **bookmarks**, since multirow tabs doesn't affect the bookmarks in any way.

Check your `userChrome.css` for multirow bookmarks code (it broke like that at some point in the past), and make sure it looks like:

``` CSS
/* MULTIROW BOOKMARKS */

#PersonalToolbar {
  max-height: unset !important}

#PlacesToolbar > hbox:first-child {
  display: block}

#PlacesToolbarItems {
    display: flex;
    flex-wrap: wrap}
```
