### ISSUE TITLE
Color variables

### ISSUE THREAD

**Issue by tugl** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#80]
Hello, appreciate the theme. I've managed to change several colors, just wondering what variables are for these?

 White selection in findbar 
![image](https://user-images.githubusercontent.com/61476585/92194638-2cc6e400-ee39-11ea-93ba-be3565fb13b8.png)

 Right click menu blue hover
![image](https://user-images.githubusercontent.com/61476585/92194660-381a0f80-ee39-11ea-9245-411818e3c49d.png)

 Scrollbar blue hover (thumb and track are not blue)
![image](https://user-images.githubusercontent.com/61476585/92196403-36524b00-ee3d-11ea-9b45-6ef1edbed0d8.png)

Thanks!

**Comment by Izheil** [comment]
The selection wasn't changeable before, but it should now after the last commit I pushed with the variable that affects all other selections, which is `--Text-selection-bg-color`.

Context menu highlights (color on hover) are changed through `--Context-menu-highlight` variable.

To change the color of the scrollbar you'd have to change a few colors in **scrollbars.as.css** file, so instead I'd recommend using the pre-made ones in the [Alternative scrollbars](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Full%20dark%20theme/Alternative%20scrollbars%20%26%20tooltips/Alternative%20scrollbars) section of the repo.
Just remove the **scrollbars.as.css** file you have, and replace it with one of the scrollbar files in there that you like.

If you still want to edit the **scrollbars.as.css** file yourself, you'll need to change the background-color of `scrollbar:hover thumb[orient="vertical"], scrollbar:hover thumb[orient="horizontal"]` and their `:active` counterparts to change the hover color of the thumb.

**Comment by tugl** [comment]
Awesome, thanks!

Do you happen to know a fix to the white flash when launching Firefox and opening new tabs?
I've tried ui.systemUsesDarkTheme set to 1 and true

**Comment by Izheil** [comment]
This rule in userChrome should already be doing that:

``` CSS
/* v Fix to make the pre-render loading page dark instead of white v */
#tabbrowser-tabpanels {background-color: #202025 !important}
```

...But that only applies to page pre-rendering, so for new tabs (I don't think it's possible to change the color of the first seconds of Firefox launch, but it will at least appear as white for a shorter time) you might need to change the color of `about:blank` (Don't do it with usercontent.css, it creates some problems with certain sites and addons that use it as a transparent overlay).
The fastest way is to change the default background color to dark (with light text) in `about:preferences` -> General category -> Language and appearance section -> Colors -> Background.

The only downside is that some pages that don't change their background color from the default (mostly some very few news sites) will show that background color instead of their regular white (if you are using a global dark theme with stylus or dark reader like addons this shouldn't be an issue), making some of their texts hard to read.

**Comment by tugl** [comment]
I see, I'm a user of Dark reader as well. 

What would be the line to change the blue highlight color?
![image](https://user-images.githubusercontent.com/61476585/92282068-e752f700-eeca-11ea-9bd9-a981310ef7e4.png)

**Comment by tugl** [comment]
Also after installing the theme, there seems to extra scrollbars everywhere (Discord web for example)
Would there be a way to not display these scrollbars?

![image](https://user-images.githubusercontent.com/61476585/92286025-d8bd0d80-eed3-11ea-90fc-c71dded9f182.png)

**Comment by Izheil** [comment]
> 
> 
> I see, I'm a user of Dark reader as well.
> 
> What would be the line to change the blue highlight color?
> ![image](https://user-images.githubusercontent.com/61476585/92282068-e752f700-eeca-11ea-9bd9-a981310ef7e4.png)

The theme doesn't change this on any non `about:` page (or support.mozilla/addons.mozilla).

You can change it adding this to `userContent.css` (changing the background-color and color to whichever ones you want of course):

``` CSS
@-moz-document url-prefix(http) {
    /* Background-color should be self-explanatory. Color changes text color. */
    *|*::selection {
        background-color: red !important;
        color: #fff !important;
    }
}
```

As for the second, scrollbars should only appear when necessary, the theming doesn't change that. 
Are you sure they didn't appear before? (They might not have been visible due to having the same background color as the element they were in)

For what I'm seeing Discord web forces scrolls to be always visible using `overflow: hidden scroll;` on most it's elements (which tells it to always hide any element that doesn't fit on screen and always show scrollbars, even when there are not overflowing elements).

You can check this by removing the scrollbars file (`userContent.css` still applies a basic theming to the scrollbars which shows when not having the .as.css file) and changing the scrollbar background color (`--scrollbars-track-color`) to something more visible like red.

To fix it for discord web app you can just add this to your `userContent.css` file:

``` CSS
@-moz-document domain("discord.com") {
    div[style^="overflow"] {overflow: auto !important}
}
```

**Comment by tugl** [comment]
Thanks. 

This is the vanilla server list (no scrollbar but still scrollable:
![image](https://user-images.githubusercontent.com/61476585/92299230-89e89580-ef1e-11ea-9fb0-b32572afbca8.png)

After theming and with the new code above, you can see 2 scrollbars:
![image](https://user-images.githubusercontent.com/61476585/92299256-b69cad00-ef1e-11ea-93b9-fe60a0f1c321.png)

**Comment by Izheil** [comment]
For me it shows the scrollbars on that section even with vanilla Firefox but not on the others.
Alright, try with this instead:

``` CSS
@-moz-document domain("discord.com") {
    div[style^="overflow"] {
        overflow-y: auto !important;
        margin-right: -16px}
    
    div[style^="overflow"] > div {
        padding-right: 16px}
}
```

It should hide scrollbars completelly but keep scrollability.

**Comment by tugl** [comment]
This does hide horizontal bars and inside right click menus.

The server list still has a vertical scrollbar. I'm thinking maybe it's from .as.css files?
![image](https://user-images.githubusercontent.com/61476585/92313069-2a799c80-ef95-11ea-854b-a1f162560c21.png)

**Comment by Izheil** [comment]
The `.as.css` scrollbar files replace the scrollbar completelly, replacing the default Firefox look, which makes it impossible to theme them using the `scrollbar-color` or `scrollbar-width` properties that let random sites or userstyles do a basic recolor of the scrollbars.

Usually it's unadvised for websites to theme scrollbars colors through only CSS, because people might want to use their own like in this case, so usually ones who want to create their own scrollers use javascript to render their own... but discord web is doing some weird things to hide the scrollbars. Instead of just hiding the scrollbars with scrollbar-width or adding negative margins, it decided to paint the scrollbars transparent (which is why they don't appear to be there in vanilla version).

The .as.css file doesn't take the arguments from scrollbar-color, so of course it ignores this and shows them.

It seems to be a issue with how they made their site, since even if you weren't using .as.css and was just using stylus with a theme to override scrollbars the issue would still appear (they just didn't think that people would want to customize the scrollbars I guess).

Anyway, I can't seem to replicate the servers sidebar keeping the scrollbar, but you can try with this and see if it helps:

``` CSS
@-moz-document domain("discord.com") {
    div[style^="overflow"], div[class*="scroller"] {
        overflow-y: auto !important;
        margin-right: -16px !important}
    
    div[style^="overflow"] > div, div[class*="scroller"] > div {
        padding-right: 16px !important}
}
```

Alternatively you can just fetch the lastest `[userContent.css](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Full%20dark%20theme/userContent.css)` file from the repo and remove the `scrollbars*.as.css` file you had. The lastest change which will paint the scrollbars dark with a basic dark recolor like before, but will now respect sites that theme the scrollbars.

**Comment by tugl** [comment]
This new code addition fixed the server list scrollbar. Thanks again for all the help. 
Feel free to close this.

```css
@-moz-document domain("discord.com") {
    div[style^="overflow"], div[class*="scroller"] {
        overflow-y: auto !important;
        margin-right: -16px !important}
    
    div[style^="overflow"] > div, div[class*="scroller"] > div {
        padding-right: 16px !important}
}
```
