### ISSUE TITLE
[BUG] modify menu bar properties and few other things

### ISSUE THREAD

**Issue by foxfoxgo** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#83]
hello, 

not a bug but didn't find if you have kind of official topic somewhere

so, thank you for all your scripts! that makes me use Firefox a bit more these last times

I'm running FF72/windows 7 with aero enabled and for now I've just copy/paste main Full dark theme's css in chrome folder, no other modification. As you can see in the image below, the menu bar is almost unreadable (too transparent, too much glowing effect, blurred?). What should I modify to customize this?

![menubar_too_blury](https://user-images.githubusercontent.com/34553468/92611138-c61e4c00-f2b8-11ea-8134-53516a8a54a9.PNG)

Additionally, the 2nd image below shows the customize page, there is no background, may I ask you the property to modify to add some background color or image?

![customize_no_bckgrd](https://user-images.githubusercontent.com/34553468/92611182-d1717780-f2b8-11ea-87f5-204a7f81d2bc.PNG)

Finally, do you have some index of the code's main sections, just to ease 'exploration' :)

Thank you

**Comment by Izheil** [comment]
Yes, there are some issues on Windows 7...
Windows 7 handles the background color of the windows, which makes the default themes not look too good unless you have transparency on... which creates other issues.

Anyway, the lastest commit should fix that issue, or you can just change [these](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/7bbadcc331afbb7270a455f5053868d277044e03).

As for the glowing text of the menu... there is nothing in the code that sets a glow for them (The only glow effect in the code applies to the favicons inside the tabs for better visibility on dark tabs), so it must be something from the theme (either Firefox theme or Windows theme) you are using (I tested on an old laptop I had on W7 and it displayed them correctly with default dark theme and userChrome from here at least).

A possible fix would be adding a background color to them and forcing some color for the text to see if that solves the issue:

``` CSS
/* This changes the background color behind tabs and the menu bar */
#titlebar, #main-menubar > menu  {
    background-color: #222 !important
}

/* This changes the text color of the elements on the menu bar */
#main-menubar label {
    color: #fff !important
}
```

**Comment by foxfoxgo** [comment]
thank you for your answer, 

I'm already using last version.

titlebar and main-menubar properties could be ok except the background of all the drop down menus reset to grey default; plus, what ever color or transparency I use it is not taken into account. Also tried to set only one prop at a time or insert at different locations in the css, no change.

In windows theme I only modified windows color (to sky blue) and I use dark theme in firefox (tested with default theme, all remain grey/white). I reinstall an old pc with new drive, Seven and nvidia are up to date, maybe something is missing, I will try with other FF versions too...

any case, most important for me is the dark menus backgrounds ;)

**Comment by Izheil** [comment]
Yep, try with this instead:

``` CSS
/* This changes the background color behind tabs and the menu bar for those using the default dark theme on Windows 7. */
#TabsToolbar, #toolbar-menubar {
    background-color: #111 !important
}

#main-menubar label {
    color: #fff !important
}
```
