### ISSUE TITLE
[REQUEST] Tab separator is missing when using the standalone patcher

### ISSUE THREAD

**Issue by explor202** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#98]
When using the standalone patcher for multi-row tabs, the tab separator is no longer visible. When the patch is removed, the separator is visible. Can an option be added to the patcher to make the separator visible? 

![ScreenShot001](https://user-images.githubusercontent.com/13698250/101285051-cf7c5f00-37a8-11eb-9d4a-39dbc2616b9a.jpg)

**Comment by Izheil** [comment]
I updated Multirow tabs to respect tab separators now.
They were removed to match the theme from the repo, and I forgot to put that in `userChrome.css` instead, but it's as it should now.

You can get the updated version from the [1.7.9 release](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases).

**Comment by explor202** [comment]
Thank you, the tab separators appear as expected. Great work on this project!

**Comment by explor202** [comment]
Thanks for the quick fix regarding the separator. Can you tell where in the .css file I can adjust the thickness of the separator?

________________________________

**Comment by Izheil** [comment]
If you are using the `userChrome.css` file of this repository, in these lines:

``` CSS
.tabbrowser-tab::after {
  opacity: 1 !important;
  border-left: 1px solid rgba(255,255,255, .15) !important}
```
^ Change "1px" from the border-left attribute to the size in pixels you want, like for 3px, it would end up like `border-left: 3px solid rgba(255,255,255, .15) !important}`

If you are using your own [userChrome](https://www.userchrome.org/) (Because you only want to change the thickness of the separator but not the whole dark theme that comes with the userChrome from this repository), just add this line to your custom userChrome instead:

``` CSS
.tabbrowser-tab::after {
    border-left-width: 2px !important;
}
```
